apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: antonlarichev/converter:v1.0
        imagePullPolicy: Always
        env:
        - name: AMQP_QUEUE
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_QUEUE
        - name: AMQP_EXCHANGE
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_EXCHANGE
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_USER
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_PASSWORD
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_HOSTNAME
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - containerPort: 80