apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-deployment"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
        imagePullPolicy: Always
        resources:
          limits: {{ .Values.app.limits | toYaml | nindent 14 }}
        ports:
        - containerPort: {{ .Values.app.port}}
